apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: bookinfo-prd-ratings
  namespace: student68-bookinfo-prd
spec:
  rules:
  - host: bookinfo.opsta.net
    http:
      paths:
      - path: /student68/ratings(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: bookinfo-prd-ratings
            port:
              number: 8080